import React, { useState } from "react";
import { motion } from "framer-motion";
import { Link } from "react-router-dom";
import { Shield, MessageCircle, Send, ChevronDown, ChevronUp, HelpCircle, AlertTriangle, Droplets, Mountain, ShieldCheck } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import ThemeToggle from "@/components/ThemeToggle";

interface FAQ {
  id: string;
  question: string;
  answer: string;
  category: string;
  icon: React.ElementType;
}

interface CommunityQuestion {
  id: string;
  user: string;
  question: string;
  answer: string;
  timestamp: string;
  votes: number;
}

const faqs: FAQ[] = [
  { id: "1", question: "What should I do during a flash flood?", answer: "Move to higher ground immediately. Avoid walking or driving through flood waters. Stay away from rivers, streams, and drainage channels. Call emergency services at 1122 if you need rescue. Keep emergency supplies ready including water, food, and first aid.", category: "Floods", icon: Droplets },
  { id: "2", question: "How does ResQ verify crisis information?", answer: "ResQ uses an AI-powered NLP engine that cross-references incoming reports with verified sources like NDMA, PDMA, and trusted news agencies (ARY, Geo). Each report receives a trust score based on source reliability, similar report clustering, and geotagging verification.", category: "AI Verification", icon: ShieldCheck },
  { id: "3", question: "What to do during an earthquake?", answer: "Drop, Cover, and Hold On. Stay indoors if you're inside — get under a desk or table. Stay away from windows and heavy objects. If outdoors, move to an open area away from buildings. After shaking stops, check for injuries and be prepared for aftershocks.", category: "Earthquakes", icon: Mountain },
  { id: "4", question: "How can I become a verified volunteer?", answer: "Sign up on ResQ and select 'Volunteer' role. Go to the Verification page and submit your CNIC (front and back). Our team reviews documents within 24-48 hours. Once verified, you can submit priority reports and help moderate community information.", category: "Volunteering", icon: ShieldCheck },
  { id: "5", question: "What are safe routes and how are they generated?", answer: "Safe routes are alternative paths generated by our GIS system when a crisis blocks a major road. The system considers current crisis locations, road conditions, and traffic data to suggest the safest and fastest alternative routes.", category: "Navigation", icon: AlertTriangle },
  { id: "6", question: "How do voice alerts work?", answer: "ResQ provides voice alerts in Urdu and English. When a critical alert is verified, audio notifications are automatically generated and broadcast to users in their selected language, ensuring accessibility for non-literate users.", category: "Alerts", icon: HelpCircle },
];

const communityQuestions: CommunityQuestion[] = [
  { id: "1", user: "Ahmed K.", question: "Is the GT Road from Lahore to Islamabad open today?", answer: "Yes, GT Road is currently clear. There was minor flooding near Jhelum but it has been resolved. Safe to travel.", timestamp: "2 hours ago", votes: 24 },
  { id: "2", user: "Fatima S.", question: "Where are the nearest shelters in Peshawar?", answer: "PDMA Emergency Camp on University Road and Al-Khidmat Center near Hayatabad are both open. Check the Shelter Finder for live capacity updates.", timestamp: "4 hours ago", votes: 18 },
  { id: "3", user: "Ali R.", question: "How accurate is the AI trust score?", answer: "Our NLP engine achieves 87% accuracy in detecting misinformation based on testing with 15+ users across Pakistan. Reports verified by multiple sources get higher trust scores.", timestamp: "1 day ago", votes: 32 },
];

const QA: React.FC = () => {
  const [openFaq, setOpenFaq] = useState<string | null>("1");
  const [newQuestion, setNewQuestion] = useState("");

  return (
    <div className="min-h-screen bg-background">
      <nav className="sticky top-0 z-40 border-b border-border/50 bg-background/80 backdrop-blur-xl">
        <div className="mx-auto flex h-14 max-w-7xl items-center justify-between px-4">
          <Link to="/" className="flex items-center gap-2">
            <div className="flex h-8 w-8 items-center justify-center rounded-lg bg-primary"><Shield className="h-4 w-4 text-primary-foreground" /></div>
            <span className="font-display text-lg font-bold text-foreground">ResQ</span>
          </Link>
          <div className="flex items-center gap-3">
            <ThemeToggle />
            <Link to="/dashboard"><Button variant="outline" size="sm">Dashboard</Button></Link>
          </div>
        </div>
      </nav>

      <main className="mx-auto max-w-4xl px-4 py-8">
        <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }}>
          <h1 className="mb-2 font-display text-3xl font-bold text-foreground">❓ Q&A & Crisis Preparedness</h1>
          <p className="mb-8 text-muted-foreground">Find answers to common questions and ask the community</p>

          {/* FAQs */}
          <section className="mb-12">
            <h2 className="mb-4 font-display text-xl font-semibold text-foreground">Frequently Asked Questions</h2>
            <div className="space-y-3">
              {faqs.map((faq) => (
                <motion.div
                  key={faq.id}
                  layout
                  className="rounded-2xl border border-border bg-card overflow-hidden"
                >
                  <button
                    onClick={() => setOpenFaq(openFaq === faq.id ? null : faq.id)}
                    className="flex w-full items-center gap-3 p-4 text-left"
                  >
                    <div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-lg bg-primary/10">
                      <faq.icon className="h-4 w-4 text-primary" />
                    </div>
                    <div className="flex-1">
                      <p className="text-sm font-medium text-foreground">{faq.question}</p>
                      <span className="text-[10px] text-muted-foreground">{faq.category}</span>
                    </div>
                    {openFaq === faq.id ? <ChevronUp className="h-4 w-4 text-muted-foreground" /> : <ChevronDown className="h-4 w-4 text-muted-foreground" />}
                  </button>
                  {openFaq === faq.id && (
                    <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="border-t border-border px-4 pb-4 pt-3">
                      <p className="text-sm leading-relaxed text-muted-foreground">{faq.answer}</p>
                    </motion.div>
                  )}
                </motion.div>
              ))}
            </div>
          </section>

          {/* Community Questions */}
          <section className="mb-12">
            <h2 className="mb-4 font-display text-xl font-semibold text-foreground">Community Questions</h2>
            <div className="space-y-3">
              {communityQuestions.map((q) => (
                <div key={q.id} className="rounded-2xl border border-border bg-card p-4">
                  <div className="mb-2 flex items-center gap-2">
                    <div className="flex h-7 w-7 items-center justify-center rounded-full bg-primary/10 text-xs font-bold text-primary">
                      {q.user[0]}
                    </div>
                    <span className="text-sm font-medium text-foreground">{q.user}</span>
                    <span className="text-xs text-muted-foreground">• {q.timestamp}</span>
                  </div>
                  <p className="mb-2 text-sm font-medium text-foreground">{q.question}</p>
                  <p className="mb-3 rounded-xl bg-secondary/30 p-3 text-sm text-muted-foreground">{q.answer}</p>
                  <div className="flex items-center gap-2 text-xs text-muted-foreground">
                    <button className="flex items-center gap-1 rounded-full bg-primary/5 px-2 py-0.5 hover:bg-primary/10">
                      👍 {q.votes}
                    </button>
                    <button className="flex items-center gap-1 rounded-full bg-primary/5 px-2 py-0.5 hover:bg-primary/10">
                      💬 Reply
                    </button>
                  </div>
                </div>
              ))}
            </div>
          </section>

          {/* Ask Question */}
          <section className="rounded-2xl border border-border bg-card p-6">
            <h2 className="mb-4 flex items-center gap-2 font-display text-lg font-semibold text-foreground">
              <MessageCircle className="h-5 w-5 text-primary" /> Ask a Question
            </h2>
            <Textarea
              placeholder="Type your question about crisis safety, routes, or shelters..."
              value={newQuestion}
              onChange={(e) => setNewQuestion(e.target.value)}
              className="mb-3 min-h-[100px] resize-none rounded-xl"
            />
            <Button className="gap-2 rounded-xl" onClick={() => { setNewQuestion(""); }}>
              <Send className="h-4 w-4" /> Submit Question
            </Button>
          </section>
        </motion.div>
      </main>
    </div>
  );
};

export default QA;
